services:
  app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app:delegated
    environment:
      DATABASE_URL: "file:./dev.db"
      NODE_ENV: development
    command: npm run dev
