import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col flex-wrap gap-2 bg-black justify-between relative h-[100vh]">
          <header
            className="h-12"
            style={{
              backgroundColor: "var(--foreground)",
              color: "var(--text)",
            }}
          >
            Header
          </header>
          <main
            className="max-w-5xl mx-5 lg:mx-auto w-full min-h-[60vh] flex justify-center items-center"
            style={{ backgroundColor: "var(--color-purple)" }}
          >
            {children}
          </main>
          <footer
            className="h-20"
            style={{
              backgroundColor: "var(--foreground)",
              color: "var(--text)",
            }}
          >
            Footer
          </footer>
        </div>
      </body>
    </html>
  );
}
